version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mesto-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/mesto
    depends_on:
      - mongo
    networks:
      - mesto-network
    mem_limit: 200m
    memswap_limit: 250m

  mongo:
    image: mongo:6
    container_name: mesto-mongo
    volumes:
      - mongo_mesto_data:/data/db
    networks:
      - mesto-network
    mem_limit: 128m
    memswap_limit: 150m
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    container_name: mesto-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - mesto-network
    mem_limit: 120m
    memswap_limit: 150m

volumes:
  mongo_mesto_data:

networks:
  mesto-network:
    driver: bridge
